### ISSUE TITLE
App is not launching, it is asking for Google login.

### ISSUE THREAD

**Issue by garcialopezco** [pogo-account-checker/Pogo-Account-Checker#7]
According to use instructions, I should be able to open the app and set all the necessary settings and grant permissions. Instead, the app at first launch is asking for Google login and is failing with every account I tried.

Android Version: 8.0.0
Model: Moto Z(XT1650-03)
Magisk Version: 20.3

![Google Login issue](https://user-images.githubusercontent.com/728524/82522706-d6cf6a00-9aef-11ea-8efd-6fa7ac7f4ef0.jpeg)

**Comment by daangroot** [comment]
Has been fixed, thanks for reporting.
